logging:
  level:
    de:
      mbur: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:13316/datatest
    username: data-test-user
    password: Das_ist_g3hEIm
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

#    hibernate:
#      ddl-auto: create-drop